version: '3.6'

volumes:
  postgis-data:

services:

  postgres:
    image: kartoza/postgis:14-3.1
    container_name: postgres_water
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis

    ports:
      - "5432:5432"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - postgis-data:/var/lib/postgresql

  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin_water
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "16543:80"
    depends_on:
      - postgres

  api:
    image: axkeyz/water:v0.7-p1
    container_name: api_water
    env_file:
      - .env
    environment:
      DB_HOST: postgres_water
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - postgres